### ISSUE TITLE
Reorganization of the folders

### ISSUE THREAD

**Issue by raultron** [im-Kitsch/RMR_sensor_fusion#1]
I think a proper folder structure should be comprised of two folders for the moment. One folder named "data" and another folder called "src" (here goes the C/C++ source code of your project), don't include compiled binaries on the "src" folder.

Inside "data" you can upload later the final pdf of the report and the final slides, you can also have a folder inside "data" named "literature" were you can put all the relevant papers. Place inside "data" all the logs and documents that you want to create for the project in proper folders. For example, you should move the files "Basic Notes.md" and "WorkPlan.md" to a folder inside "data".

The README belongs to the root folder as it is right now.

So the repo should look:

/data
/src
README.md

Remember that all the code, comments and documentation should be in English and take a Git tutorial so you can properly use the Code Versioning tools instead of using this like a Dropbox folder.

Cheers!

**Comment by raultron** [comment]
it has been a week already....

**Comment by im-Kitsch** [comment]
## The problmen 5.4:
The driver in the [website](http://wiki.asctec.de/display/AR/Telemetric+Feedback) doesn't work.  The PC can not recognize the device.
One of the motor seems to work not regularily.

**Comment by raultron** [comment]
It seems to be organized now, I am going to close the issue now.
