### ISSUE TITLE
Unwanted union behavior (incl. ** Workaround **)

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#12]
Hello @raultron, hello @Dino,
as Dino pointed out while last meeting we have some problems using the following union:

```
typedef union {
	struct {
		/***	--- Protocol head --- ***/
		uint8_t startByte; //Status Flags; 0: Valid, 1: ...

		/*** 	--- Sensory Data --- ***/
                int angle_pitch;
		int angle_roll;
		int angle_yaw;

                 /*** --- Protocol Footer --- ***/
		uint8_t checksum;
	} protocol_s;

	uint8_t bytestream[num_sum];
}protocol_u;
```

While using this union the following irregularity occurs:
![union_error](https://user-images.githubusercontent.com/38527505/41201506-037d1470-6cc2-11e8-801e-b588f1c7d935.jpg)

As you can see in the picture the union is not working as expected. For the first four variables you can see the correct alignment between the struct  `protocol_s` and the bytearray `bytestream`. But when you compare the last byte in the union (checksum = 7), you can see that bytestream[13] (= 0) is not consistent anymore.
As Dino already mentioned, this problem is called **Padding**. Padding baiscally is called the way the C compiler lays out basic C datatypes in memory in order to make memory accesses faster (see [detailed explanation)](http://www.catb.org/esr/structure-packing/). In our specific case, the compiler seems to add some Zero-Bytes after `angle_yaw` in order to place `checksum` at an aligned position for faster access. To avoid that compiler optimization we tried to use 
```
#pragma pack(push,1) 
typedef union {
[...]
}protocol_u;
#pragma pack(pop)
```

That is working quite good for the Nucleo, no padding anymore so the alignment is like expected. The only thing that should be mentioned is the swap between MSB and LSB while using the `#pragma`. But this is easily corrected by a simple for - loop, which is swapping the Bytes. 

Unfortunately for the HLP the `#pragma` isn't working with error message:

> protocol.h:19: warning: #pragma pack(push[, id], <n>) is not supported on this target
> protocol.h:51: warning: #pragma pack(pop[, id], <n>) is not supported on this target

I haven't found a solution, yet.

** Workaround **
We found out by testing that padding is only used when a greater variable is followed by a smaller variable, so for example
```
		uint8_t var1; //8Bit
                int var2; //32Bit
		int var3; //32Bit
		int var4; //32Bit
                uint8_t var5; //8Bit (PADDING)
```
uses padding, while 
```
		uint8_t var1; //8Bit
                uint16_t var2 //16Bit
                uint16_t var3 //16Bit
                int var4; //32Bit
		int var5; //32Bit
		int var6; //32Bit
```
uses no padding at all and is working for us. Of cause we are not 100% sure if that works in any situation, but it works in 5 out of 5 tested ones. We are using that method while we don't know how to fix that error.  Anyway, the limitation is not that big, you just have to be aware about the right order of your variables. To see our current working solution, visit [our Code](https://github.com/im-Kitsch/RMR_sensor_fusion/blob/0d6a5843f4dae6eb966fb8e0cf34a057b3f3401d/src/AscTec_SDK_v3.0/protocol.h#L20-L62).

Many thanks in advance for your time and help!

**Comment by im-Kitsch** [comment]
Besides #pragma() methods I also find another solution today, it uses another keyword "\_\_attribute__ ((\_\_packed__))".  An example is like this.

typedef struct ppp{
     char c;
     int  i;
     char cc;
      int ii;
} \_\_attribute__ ((\_\_packed__))  ppp;

I test it on Nucleo firstly use sizeof() function to test the struct size and then create a union which includes this struct and a char array with same length.  And the size is still right size: 10. And when the element in array is operated, the element in struct is also rightly operated. 
And it is also tested in HLP IDE. With this demo struct, project can be built without error or warning like pragma. And I will test data operating on HLP board at Monday.
A more formal code snippet link will be updated later. (anyone copy code to issues or from issues, be careful of " \_" in markdown)

And a small addition, the padding relates to alignment. For the reason, the mechanism, man can just refer to [wikipedia](https://en.wikipedia.org/wiki/Data_structure_alignment).

~~By the way, as I have googled, it seems to suggest to avoid padding problem by reordering the sequence of data. Because it's not well to obey the alignment mechanism. If we can define the whole protocol we can truely "softly" avoid the padding. This point hasn't been seriously learned. Because padding will still occur while using single sensor protocol. Just mark it here.~~

**Comment by malbreitenbach** [comment]
Great to see, you found an alternative to the '#pragma'! Would love to hear the result on monday. 

>If we can define the whole protocol we can truely "softly" avoid the padding. 

I guess this is related to the ** workaround ** because we avoid padding by ordering of variables? We have to keep in mind that there is no such thing like "whole protocol" because most likely there will be added some new sensory later on.

**Comment by im-Kitsch** [comment]
@malbreitenbach 
yes, So I just mark that as a little addition and want to update it later. Don't take it the last sentences so seriously.   ┭┮﹏┭┮ Exactly there will be some new sensory like PX4Flow. ┭┮﹏┭┮ 
But let's focus on the "hard core" solution. We need it anyway.  We don't have disagreement at this point and I will update progress Monday.
Cheers.

**Comment by im-Kitsch** [comment]
\_\_attribute\_\_ works in HLP.
I make this small test in HLP. Operation the element in array and in struct to see if the other in union is also rightly operated.

```c
//zhiyuan
typedef struct teststru{
	char a1;
	int a2;
	char a3;
	int a4;
	char a5;
} __attribute__((packed))  teststru;
union{
	teststru  stru;
	char arr[11];
} testunion;
//zhiyuan
void SDK_mainloop(void)
{
	static int i =0;
	if (i == 0)
	{
		testunion.arr[10] = 1;
		i++;
	}
	else if(i == 1){
		testunion.arr[10] = 12;
		i++;
	}
	else if(i==2){
		testunion.stru.a5 = 5;
		i = 0;
	}
	if(i >= 0)
	{
		i = i +1;
		i = i-1;
		i = i*1 ;
	}; // for breakpoint
.................
```
And the operation is proved to be true. The package is compactly "packed". And padding is avoided.

![image](https://user-images.githubusercontent.com/33943000/41255135-d9906b9e-6dc5-11e8-8813-b698abd2a002.png)
![image](https://user-images.githubusercontent.com/33943000/41255139-dd8f8766-6dc5-11e8-9dbb-c22a5d1ea5c2.png)
![image](https://user-images.githubusercontent.com/33943000/41255144-e0092ba0-6dc5-11e8-9474-4ace1b77fa8c.png)

**Comment by malbreitenbach** [comment]
Great to see it's working! I will test it tomorrow in our protocol and close the issue afterwards.

**Comment by malbreitenbach** [comment]
Test was successful today. The union is not a problem anymore. 
By the way: While using the `#pragma` and `__attribute__((packed))`, little and big endian are changed! But we don't have to care about it, because we use in on both structs on both processors. The function [changeMSB_LSB()](https://github.com/im-Kitsch/RMR_sensor_fusion/blob/0d6a5843f4dae6eb966fb8e0cf34a057b3f3401d/src/Nucleo_V2/Src/protocol.c#L59-L104) is therefore not needed anymore. I will close the ussue if everyone agrees.

**Comment by im-Kitsch** [comment]
@malbreitenbach  It's great to hear that we don't need to care MSB and LSB. Great!

**Comment by raultron** [comment]
Great to know that it is working, I also learned something.
