### ISSUE TITLE
Code profiling

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#14]
The last days we have tried to figure out what parts of our code are time expensive. We followed several 
approaches, but not with 100% success, yet. Best approach was using a timer and compare the counter at certain places in the code. We are able to store the current counter value inside a variable, but we are not able to read this variable while debugging (Watch expression isn't working reliably ). So we tried to read the counter value directly out of the memory (see below)

![timer1](https://user-images.githubusercontent.com/38527505/41416974-67f4fca6-6fec-11e8-9218-e7882a42389b.png)

But it seems like 'pause at breakpoint' -> 'read the value' -> 'run' -> 'pause at next breakpoint' -> [...] is not accurate enough, because the 'run & pause' also seems to need some time.

So we need to find a solution to store the current counter inside a variable.
We already tried:
```
volatile unsigned long ticks = T1TC; //Reading '0xffffffff' at any time
volatile unsigned int ticks = T1TC; //Reading '0xffffffff' at any time
volatile uint32_t ticks = T1TC; //Reading '0xffffffff' at any time

unsigned long ticks = T1TC; 
volatile unsided long avoidOptimization = ticks; 
/* Works sometimes if you set the breakpoint right afer the declaratoin */
```

Unfortunatly we haven't found a solution that is working in any time, so maybe someone has an idea about that? @raultron @im-Kitsch @Dinu

**Comment by raultron** [comment]
Please refer to the actual code that you are using (branch and line number) in the Github repo website you can go to the code and on the left side you will find the links that you can paste here. I need to see what you are doing. I know it is dumb but did you enable the timer? and did you configure correctly the prescaler?

To enable the timer you have to set the bit 0 of the TCR register.

**Comment by raultron** [comment]
... also not related, but if you have time we would like to have a meeting tomorrow at 3pm, please discuss within your group if you can be there and send us an email with the confirmation

**Comment by malbreitenbach** [comment]
Thanks for the reply!
Yes, the timer is enabled, you can see it in the memory as well. I added some notes to the picture:
<img width="800" alt="timer1" src="https://user-images.githubusercontent.com/38527505/41425252-7a4c4396-7000-11e8-94ea-343533e028a8.png">

As you can see, the TCR register is set to 1. When you watch the memory while runtime you can see that the TC is rising (like expected). So in my opinion the timer is running correctly. The prescaler is set to 0xFFFF (very high for testing reasons). See the initialization sequence [here](https://github.com/im-Kitsch/RMR_sensor_fusion/blob/37a6fbe253d5f8464007bd5daed6f2ae52cc8705/src/AscTec_SDK_v3.0/system.c#L197-L206).
The main problem is (how I think) not the timer but the reading out out the Timer Counter (TC) register by the debugger. 

We can do it by 
```
unsigned long ticks = T1TC; 
volatile unsided long avoidOptimization = ticks; 
```
but it is extremly hard to acutally see the value of `ticks` inside the debugger. In 99 out of 100 cases it is not showing any value because `ticks` is not `volatile`. Just when you place the breakpoint at some speacial point (a few lines after the allocation) it is showing the expected timer counter value correctly.  When you declare `ticks` as `volatile` it just shows '0xffffffff' all the time.
