### ISSUE TITLE
The problmen 5.4:

### ISSUE THREAD

**Issue by im-Kitsch** [im-Kitsch/RMR_sensor_fusion#2]
The driver in the [website](http://wiki.asctec.de/display/AR/Telemetric+Feedback) doesn't work.  The PC can not recognize the device.
One of the motor seems to work not regularily.

**Comment by raultron** [comment]
I had two students working on the Firefly before:

- Xun Tong <tongxun0725@gmail.com>
- Nihad Saliji <nihad.sa@hotmail.de>

They are going to have their final Master presentation next Wednesday afternoon. It may be nice for you to attend the presentation. Also, you should meet with them so they can explain to you what they did to the Firefly. Please set up this meeting and then let me know what you discussed.

**Comment by malbreitenbach** [comment]
I will contact them right now for a meeting as fast as possible. 
@im-Kitsch Have you already tried it under Linux?

Cheers!

**Comment by im-Kitsch** [comment]
@malbreitenbach unfortunately that day we have not tried in Linux. We try alternatively to install the new driver in website. And the physically interface of XBEE seems to conflict to other communication interface.
