### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#20]
Hello @raultron and @Dinu,
how should we refer to our written code? Using a github-link or better adding it to the attachments?

Thanks for reply in advance!

**Comment by malbreitenbach** [comment]
Also interesting would be the title of the paper? 
Shall we decide it by ourselves?

**Comment by malbreitenbach** [comment]
Hi @raultron,
we are nearly done with the paper. If you want to, you can [have a look and give some feedback](https://github.com/im-Kitsch/RMR_sensor_fusion/tree/data/data/paper).

It also would be very nice, to get some answers on the questions above :+1: 

Have a nice day!

EDIT: How should we include the Tutorials? Adding it to the bibliograpy?

**Comment by raultron** [comment]
Question 1: Better add the Github link.
Question 2: You decide the title.
