### ISSUE TITLE
Meeting with Tong Xun

### ISSUE THREAD

**Issue by im-Kitsch** [im-Kitsch/RMR_sensor_fusion#3]
1. The operating system of Mastermind doesn't work now. It seems like that it's not suitable for Ubuntu 16.04 and they reinstall it as Ubuntu 12.
2. The program of HL Processor is not original version. We need to update it.
3. We can also just use the Mastermind in UAV

More things to be clarified in Friday.

**Comment by malbreitenbach** [comment]
What do mean by 3. ?

**Comment by raultron** [comment]
Well, she told me that she created some code on the HL Processor to read the measurements of the laser. If the code is OK we should integrate it into the default code for the HL Processor. Let's call it the HL_rmr_firmware (we can have versions of this firmware on Github).

**Comment by im-Kitsch** [comment]
Well, she means it's okay to use Mastermind to communicate, just as we talked in last Friday, we can just ignore Matermind now.
