### ISSUE TITLE
The small bug

### ISSUE THREAD

**Issue by im-Kitsch** [im-Kitsch/RMR_sensor_fusion#4]
@malbreitenbach  
Hi, I've been pushed the .gitignore of the truestudio project and you can also update your SPI code. Filter is not very strict because some files like .project are also tracked.
Furthermore, if you have time, can you have a try about my code in my branch? It's just a small test about LED Blinking with "i--" format delay. I can toggle the LED with button but the loop will not be excuted normally. The value shows "optimized out". Both for loop or while loop seems wired, only sometimes I make the single step debug, LED will blink. If you have time you can also take a look at it. I'm a little confused of it.
Cheers.

**Comment by malbreitenbach** [comment]
@im-Kitsch
I will test it tomorrow. To avoid the "optimized out" declare your variable as "volatile".
Cheers

**Comment by im-Kitsch** [comment]
@malbreitenbach 
Hi, thanks for your help. I add volatile keyword and it works normally. It need not to be test now and I close my branch later. And later after you have seen this issue I will close this Issue.
Thanks!  (￣▽￣)"

**Comment by malbreitenbach** [comment]
Good to hear!
