### ISSUE TITLE
Solution to the build error with Eclipse in WIN10

### ISSUE THREAD

**Issue by XianglunChen** [im-Kitsch/RMR_sensor_fusion#5]
Hi guys, try this way to solve the problem when you build AscTec_ARM in Eclipse, which like errors "child 10220(0x238) died before initialization with status code 0xC0000142" .

Copy this file to utils\bin directory (WinAVR)
[msys-1.0-vista64.zip](https://github.com/im-Kitsch/RMR_sensor_fusion/files/2002582/msys-1.0-vista64.zip)

Hope it could be useful to you.

**Comment by im-Kitsch** [comment]
Yes I also received the E-Mail of Firefly. Unbelievable it should be showed in the website of SDK obviously and we didn't find it before   ┭┮﹏┭┮  ┭┮﹏┭┮

**Comment by malbreitenbach** [comment]
Thanks, works fine for me! I don't think its obvious, they placed the information on the wrong site.
