### ISSUE TITLE
Some notes about flashing HL and plug

### ISSUE THREAD

**Issue by im-Kitsch** [im-Kitsch/RMR_sensor_fusion#6]
Flashing program to HL in win10 still doesn't work. We give up to solve selfly and wait the reply of customer service.

For the using of Ubuntu to download program, I will upload later in github.

The plug we tried to soldering and only crimping. And it actually need to be crimped rather than solder cause the socket is too small.  Not only for us but also for the UAV fans in the world a nightmare.  So we give up make it manually and search the socket already assembly with cable. 
The link are here:
[This ]( https://www.amazon.de/Cylewet-52-Flugsteuerungskabel-verschiedene-Spezifikationen-Positionsstecker/dp/B06XD3NZ5C/ref=sr_1_1?ie=UTF8&qid=1527013734&sr=8-1&keywords=df13 )is the link in amazon, it's the already finished connector. We can just destroy the plastic shell and use the cabel.  Just because the shipping is better.

[This](https://www.unmannedtechshop.co.uk/df13-to-df13-pre-crimped-diy-silicone-wire-pack-pack-of-20/) is recommended, but shipping not guranteed.
[This](https://www.digikey.com/catalog/en/partgroup/df13-series/1796?partPage=2) is also good, but it need to be read carefully.

**Comment by malbreitenbach** [comment]
Finally the problems regarding Windows 10 and Flashing the HLP are solved. There are much steps to follow so we will write a tutorial soon.
We built a cable for testing reasons which works for the moment, but is defenetly not durable.
