### ISSUE TITLE
Maximum power output of powerboard

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#8]
We plan to use the 5V and GND output of the powerboard (Firefly) to power the Nucleo due to E5V - pin.
We assume that the maximum current of 500mA (2,5W) due to the E5V-pin is enough to power the Nucleoboard (See p. 20-24 in User Manual). 
Unfortunatly we haven't found some information about the maximum power output of the powerboard yet.
If it isn't capable of powering the Nucleo, we have an alternative due to the Vin-pin, which allows 7V to 12V and can be directly connected to the battery (~11,1V).

**Comment by raultron** [comment]
status of this?

**Comment by malbreitenbach** [comment]
We are quite confident that the power board is capable to power the Nucleo because of the Nucleo's small power consumption. 
Our Cable is already prepared to power the Nucleo, so theoretical we just need to connect the cable and change some jumper positions. Regardless we hadn't find the official information of the power board's maximum output to be 100% sure, yet. We stay in contact with the support for clarification.

**Comment by malbreitenbach** [comment]
@raultron 
The support unfortunately can't give us any concrete information about the maximum power output, but they said that 500 mA (2,5W) should be fine. I already tested to power the nucleo by a 5V supply and it works fine.

I will write a tutorial about it.
