### ISSUE TITLE
Mechanical mount

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#9]
We started to design a **mount** for the Nucleo (See "data/mount"). We haven't decided where the mount should be placed onto the firefly. We basically thought about two variants with the following pros/cons:

Mounting on top | Mounting to the side
------------ | -------------
 **+** maintain the balance| **-** unbalance
**-** Covering the GPS-/magnetic sensor (possibly additional metal plate for sheelding nescessery)| **+** most likely no additional shielding nescessery

**Comment by raultron** [comment]
any development on this?

**Comment by malbreitenbach** [comment]
We designed a part of the 3D Model of the mount. To be more precise the connection: Mount <-> Nucleoboard (see "data/mount"). I would love to hear your optinion about both positions, because Dino isn't sure about it. I will track this task with higher priority from now on and work on it besides the protocol improvements.

**Comment by malbreitenbach** [comment]
@raultron I'm not sure if we can design a proper 3D mount in time while I need to focus on the (more important?) protocol. The 3D printing is taking up to 4 weeks, right?

**Comment by raultron** [comment]
Focus on the protocol
